sphinx-doc-v2-compat: 'HTML5Translator' object has no attribute 'set_first_last'
Since Sphinx-doc commit: https://github.com/sphinx-doc/sphinx/commit/a3cdd465ecf
the HTML builder outputs HTML5 by default.  The new HTML5Translator does not
have a methode named ``set_first_last``

This patch fixes error::

    Exception occurred:
      File "sphinxjp/themes/revealjs/directives.py", line 273, in visit_revealjs
        self.set_first_last(node)
    AttributeError: 'HTML5Translator' object has no attribute 'set_first_last'

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>